version: '3.8'

services:
  app:
    build: .
    container_name: ionic-biblia
    ports:
      - "8100:8100"
      - "35729:35729"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Essential for hot reload on some systems
    command: bash -c "npm install --legacy-peer-deps && ionic serve --host 0.0.0.0 --disable-host-check"
